use strict;
use Test::More 0.98;

use_ok $_ for qw(
    GraphQL::Houtou
    GraphQL::Houtou::Native
    GraphQL::Houtou::Schema::Compiler
    GraphQL::Houtou::Schema
    GraphQL::Houtou::Directive
    GraphQL::Houtou::Role::Input
    GraphQL::Houtou::Role::Output
    GraphQL::Houtou::Role::Composite
    GraphQL::Houtou::Role::Abstract
    GraphQL::Houtou::Role::Leaf
    GraphQL::Houtou::Role::Named
    GraphQL::Houtou::Role::FieldsEither
    GraphQL::Houtou::Role::FieldsInput
    GraphQL::Houtou::Role::FieldsOutput
    GraphQL::Houtou::Role::FieldDeprecation
    GraphQL::Houtou::Role::HashMappable
    GraphQL::Houtou::Type
    GraphQL::Houtou::Type::Object
    GraphQL::Houtou::Type::Interface
    GraphQL::Houtou::Type::Union
    GraphQL::Houtou::Type::InputObject
    GraphQL::Houtou::Type::Enum
    GraphQL::Houtou::Type::List
    GraphQL::Houtou::Type::NonNull
    GraphQL::Houtou::Type::Library
    GraphQL::Houtou::Type::Scalar
    GraphQL::Houtou::Promise::Adapter
    GraphQL::Houtou::Validation
    GraphQL::Houtou::XS::Validation
    GraphQL::Houtou::XS::SchemaCompiler
    GraphQL::Houtou::XS::VM
    GraphQL::Houtou::Runtime
    GraphQL::Houtou::Runtime::Compiler
    GraphQL::Houtou::Runtime::OperationCompiler
    GraphQL::Houtou::Runtime::ProgramSpecializer
    GraphQL::Houtou::Runtime::SchemaGraph
    GraphQL::Houtou::Runtime::Program
    GraphQL::Houtou::Runtime::Block
    GraphQL::Houtou::Runtime::Slot
    GraphQL::Houtou::Runtime::Outcome
    GraphQL::Houtou::Runtime::Writer
    GraphQL::Houtou::Runtime::LazyInfo
    GraphQL::Houtou::Runtime::PathFrame
    GraphQL::Houtou::Runtime::ErrorRecord
    GraphQL::Houtou::Runtime::FieldFrame
    GraphQL::Houtou::Runtime::BlockFrame
    GraphQL::Houtou::Runtime::Cursor
    GraphQL::Houtou::Runtime::ExecState
    GraphQL::Houtou::Runtime::VMCompiler
    GraphQL::Houtou::Runtime::VMDispatch
    GraphQL::Houtou::Runtime::VMProgram
    GraphQL::Houtou::Runtime::VMBlock
    GraphQL::Houtou::Runtime::VMOp
    GraphQL::Houtou::Runtime::VMExecutor
    GraphQL::Houtou::Runtime::NativeRuntime
    GraphQL::Houtou::Runtime::NativeBundle
);

done_testing;
