name: test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - perl: "5.44"
            image: perl:5.44-trixie
          - perl: "5.42"
            image: perl:5.42-trixie
          - perl: "5.40"
            image: perl:5.40-trixie
          - perl: "5.38"
            image: perl:5.38-trixie
          - perl: "5.36"
            image: perl:5.36.3-bookworm
          - perl: "5.34"
            image: perl:5.34.3-bullseye
          - perl: "5.32"
            image: perl:5.32-bullseye
          - perl: "5.30"
            image: perl:5.30-bullseye
          - perl: "5.28"
            image: perl:5.28-buster
          - perl: "5.26"
            image: perl:5.26-buster
          - perl: "5.24"
            image: perl:5.24-buster
    name: Perl ${{ matrix.perl }}
    container:
      image: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v7
      - name: Install dependencies
        run: cpanm --notest --installdeps .
      - name: Build XS distribution
        run: |
          perl Build.PL
          ./Build build
      - name: Run test
        run: ./Build test
  release-tests:
    name: Distribution release tests
    runs-on: ubuntu-latest
    container:
      image: perl:5.44-trixie
    steps:
      - uses: actions/checkout@v7
      - name: Install Minilla and dependencies
        run: |
          cpanm --notest Minilla Test::CPAN::Meta \
            Test::MinimumVersion::Fast Test::PAUSE::Permissions \
            Test::Pod Test::Spellunker
          cpanm --notest --with-develop --installdeps .
      - name: Run distribution and author tests
        run: RELEASE_TESTING=1 minil test
